server {
  listen 4321;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location = /runtime-config.js {
    add_header Cache-Control "no-store";
    try_files $uri =404;
  }

  location = /healthz {
    access_log off;
    add_header Content-Type text/plain;
    return 200 "ok";
  }
}
