#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"

docker_cmd_exists() {
  local docker_bin="${DOCKER_BIN:-docker}"
  if [[ "$docker_bin" == */* ]]; then
    [[ -x "$docker_bin" ]]
    return
  fi
  command -v "$docker_bin" >/dev/null 2>&1
}

docker_compose_ok() {
  local docker_bin="${DOCKER_BIN:-docker}"
  if ! docker_cmd_exists; then
    return 1
  fi
  "$docker_bin" compose version >/dev/null 2>&1
}

print_status() {
  local label="$1"
  local value="$2"
  printf '%-24s %s\n' "$label" "$value"
}

check_cmd() {
  local cmd="$1"
  local required="${2:-yes}"
  if command -v "$cmd" >/dev/null 2>&1; then
    print_status "$cmd" "ok"
    return 0
  fi

  if [[ "$required" == "yes" ]]; then
    print_status "$cmd" "missing"
    return 1
  fi

  print_status "$cmd" "optional-missing"
  return 0
}

check_docker_compose() {
  if ! docker_cmd_exists; then
    return 1
  fi

  if docker_compose_ok; then
    print_status "docker compose" "ok"
    return 0
  fi

  print_status "docker compose" "unavailable (check Docker Desktop WSL integration)"
  return 1
}

main() {
  local failed=0

  echo "AppFoundryLab developer doctor"
  echo
  print_status "workspace" "$ROOT_DIR"
  echo

  if docker_cmd_exists; then
    print_status "docker" "ok"
  else
    print_status "docker" "missing"
    failed=1
  fi
  check_docker_compose || failed=1
  check_cmd bash yes || failed=1
  check_cmd curl yes || failed=1
  check_cmd openssl yes || failed=1
  check_cmd go no || true
  check_cmd bun no || true
  check_cmd rustc no || true
  check_cmd cargo no || true
  check_cmd cc no || true
  check_cmd python3 no || true
  check_cmd jq no || true

  echo
  if [[ -f "$ROOT_DIR/.env" ]]; then
    print_status ".env" "present"
  else
    print_status ".env" "missing (will be created by bootstrap/dev-up)"
  fi

  if [[ -f "$ROOT_DIR/.env.docker.local" ]]; then
    print_status ".env.docker.local" "present"
  else
    print_status ".env.docker.local" "missing (will be created by bootstrap/dev-up)"
  fi

  if [[ -f "$ROOT_DIR/backend/infrastructure/certs/dev/ca.crt" ]]; then
    print_status "dev certs" "present"
  else
    print_status "dev certs" "missing (will be generated by bootstrap/dev-up)"
  fi

  echo
  if [[ "$failed" -ne 0 ]]; then
    echo "doctor result: failed"
    echo "fix required tools first, then rerun ./scripts/dev-doctor.sh"
    exit 1
  fi

  echo "doctor result: ok"
  echo "next step: ./scripts/dev-up.sh standard"
}

main "$@"
